export { usePatients, usePatient } from './usePatients'
export { useVisits, useVisit } from './useVisits'
export { useNurseDocumentation } from './useNurseDocumentation'
export { useConsultations, useConsultation } from './useConsultation'
export { usePrescriptions, useMedications, usePrescription } from './usePrescription'
export { useQueue, useQueueStats } from './useQueue'
export { useReports, useDailySummary, usePatientStats } from './useReports'
export { useAuth } from '../context/AuthContext'
